-- Baseline — the origin marker for hikyaku-api's TypeORM migration ledger.
--
-- The full schema (extensions, tables, PostGIS, RLS, functions, seed data) is
-- OWNED by the `../schema` directory and applied to Supabase out of band
-- (roles.sql -> schema.sql -> seeds/*). It is NOT recreated here.
--
-- This file is intentionally a no-op: running it against the already-provisioned
-- Supabase database must change nothing. It exists only so the `typeorm_migrations`
-- ledger has a fixed starting point that every later migration builds on.
--
-- To bootstrap a FRESH / local database: apply `../schema` first, THEN run
-- `pnpm migration:run`.
--
-- For changes this app should own going forward, add a NEW paired migration
-- (e.g. 1700000000000-add_user.sql + .ts) rather than editing this baseline.
-- Keep statements idempotent (IF NOT EXISTS / CREATE OR REPLACE).
