import { MigrationInterface, QueryRunner } from 'typeorm';
import { readFileSync } from 'fs';
import { join } from 'path';


export class PackageTimelineUuidPkAndRealtime1786261852261 implements MigrationInterface {
    name = 'PackageTimelineUuidPkAndRealtime1786261852261';

    private read(file: string): string {
        return readFileSync(join(__dirname, file), 'utf8').trim();
    }

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(this.read('1786261852261-package_timeline_uuid_pk_and_realtime.sql'));
    }

    // Best-effort structural revert. The original bigint values are gone for
    // good (that's inherent to any id-type swap) — this rebuilds a bigint
    // identity PK and re-sequences rows via ROW_NUMBER() ordered by
    // (created_at, id), so relative order is preserved even though the
    // literal numbers differ from what they were pre-migration.
    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            ALTER PUBLICATION "supabase_realtime" DROP TABLE "public"."package_timeline";
        `);

        await queryRunner.query(`
            ALTER TABLE "public"."package_timeline" DROP CONSTRAINT "package_timeline_pkey";
        `);

        await queryRunner.query(`
            ALTER TABLE "public"."package_timeline" ADD COLUMN "id_bigint" bigint;
        `);

        await queryRunner.query(`
            WITH ordered AS (
                SELECT "id", row_number() OVER (ORDER BY "created_at", "id") AS rn
                FROM "public"."package_timeline"
            )
            UPDATE "public"."package_timeline" pt
            SET "id_bigint" = ordered.rn
            FROM ordered
            WHERE ordered."id" = pt."id";
        `);

        await queryRunner.query(`
            ALTER TABLE "public"."package_timeline" ALTER COLUMN "id_bigint" SET NOT NULL;
        `);

        await queryRunner.query(`
            ALTER TABLE "public"."package_timeline" DROP COLUMN "id";
        `);

        await queryRunner.query(`
            ALTER TABLE "public"."package_timeline" RENAME COLUMN "id_bigint" TO "id";
        `);

        await queryRunner.query(`
            ALTER TABLE "public"."package_timeline" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
                SEQUENCE NAME "public"."package_timeline_id_seq"
                START WITH 1
                INCREMENT BY 1
                NO MINVALUE
                NO MAXVALUE
                CACHE 1
            );
        `);

        await queryRunner.query(`
            SELECT setval('"public"."package_timeline_id_seq"', (SELECT COALESCE(MAX("id"), 0) FROM "public"."package_timeline"));
        `);

        await queryRunner.query(`
            ALTER TABLE "public"."package_timeline" ADD CONSTRAINT "package_timeline_pkey" PRIMARY KEY ("id");
        `);

        await queryRunner.query(`
            CREATE INDEX "package_timeline_pkg_created_idx"
                ON "public"."package_timeline" USING "btree" ("package_id", "created_at" DESC, "id" DESC);
        `);

        await queryRunner.query(`
            DROP FUNCTION IF EXISTS "public"."uuid_generate_v7"();
        `);
    }
}
