services:
  scheduler:
   # For local development, build the image from the local Dockerfile to pick up changes more quickly. For production, pull from the registry.
    image: ghcr.io/whendan/whendan-scheduler:main
   # build:
   #   context: .
   #   dockerfile: Dockerfile
    ports:
      - "${PORT:-3002}:3002"
    env_file:
      - .env
    environment:
      PORT: ${PORT:-3002}
      DB_URL: ${DB_URL}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      VALHALLA_URL: ${VALHALLA_URL:-http://100.106.172.94:8002}
      VROOM_URL: ${VROOM_URL:-http://localhost:3000}
    restart: unless-stopped
  vroom:
    image: ghcr.io/vroom-project/vroom-docker:v1.15.0
    container_name: vroom
    volumes:
      - ./vroom-conf/:/conf
    environment:
      - VROOM_ROUTER=valhalla
